apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: platform/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: platform/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: apps/hello
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
