---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: platform/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: platform/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-tls
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: platform/tls
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
        - /spec/conversion
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-prometheus-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "28"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-operator-crds
    targetRevision: "*"
    helm:
      releaseName: prometheus-operator-crds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 66.2.1
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
        - values.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      releaseName: loki-stack
      values: |
        loki:
          enabled: true
          persistence:
            enabled: false
        promtail:
          enabled: true
        grafana:
          ingress:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-hello
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: apps/hello
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-cert-alerts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "32"
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: platform/observability/cert-manager-alerts
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-grafana-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "33"
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: platform/observability/grafana-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-prometheus-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "34"
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: platform/observability/prometheus-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-alertmanager-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: platform/observability/alertmanager-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-linkerd-identity
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: default
  source:
    repoURL: https://github.com/eched1/homelab-gitops.git
    targetRevision: main
    path: platform/linkerd/identity
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-linkerd-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "52"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-crds
    targetRevision: 1.8.0
    helm:
      releaseName: linkerd-crds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-linkerd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "54"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-control-plane
    targetRevision: 1.16.11
    helm:
      releaseName: linkerd
      values: |
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBdDCCARugAwIBAgIRALU5EMKDyQlOg7JJoxLfTuEwCgYIKoZIzj0EAwIwGjEY
          MBYGA1UEAxMPaG9tZWxhYi1yb290LWNhMB4XDTI2MDIyMDA3NDExNVoXDTI2MDUy
          MTA3NDExNVowGjEYMBYGA1UEAxMPaG9tZWxhYi1yb290LWNhMFkwEwYHKoZIzj0C
          AQYIKoZIzj0DAQcDQgAEhAYEkewGHxSSkExnriZh0W0c4yR5ht1GKQNQSoFdqhUM
          +0TKWrw0xNCN1in0VpOCtcCcaCO2qv6yUWwsYR2u4aNCMEAwDgYDVR0PAQH/BAQD
          AgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFIjdilS2fopHnz365bLiGzCe
          nW82MAoGCCqGSM49BAMCA0cAMEQCID3ZAJnALNathGDhyVqVZIW9lVPLjDIrnVOb
          C+svaU/iAiBiFVAHzWCgo2XkG6NyxqSNUdiQE7BPkGz0C7k88FP8vg==
          -----END CERTIFICATE-----
        identity:
          externalCA: true
          issuer:
            scheme: kubernetes.io/tls
            externalSecret: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-linkerd-viz
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "56"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-viz
    targetRevision: 30.12.11
    helm:
      releaseName: linkerd-viz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true          