apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-home-arpa
  namespace: hello
spec:
  secretName: wildcard-home-arpa-tls
  dnsNames:
    - "*.home.arpa"
    - "home.arpa"
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
