apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 2160h   # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
  dnsNames:
    - identity.linkerd.cluster.local
