apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      releaseName: loki-stack
      values: |
        loki:
          enabled: true
          persistence:
            enabled: false
        promtail:
          enabled: true
        grafana:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
